[2021-03-04 21:46:22,698] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: clean_data.merge_data 2021-03-04T21:44:31.403251+00:00 [queued]>
[2021-03-04 21:46:22,731] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: clean_data.merge_data 2021-03-04T21:44:31.403251+00:00 [queued]>
[2021-03-04 21:46:22,732] {taskinstance.py:880} INFO - 
--------------------------------------------------------------------------------
[2021-03-04 21:46:22,732] {taskinstance.py:881} INFO - Starting attempt 1 of 2
[2021-03-04 21:46:22,733] {taskinstance.py:882} INFO - 
--------------------------------------------------------------------------------
[2021-03-04 21:46:22,764] {taskinstance.py:901} INFO - Executing <Task(PythonOperator): merge_data> on 2021-03-04T21:44:31.403251+00:00
[2021-03-04 21:46:22,767] {standard_task_runner.py:54} INFO - Started process 7206 to run task
[2021-03-04 21:46:22,799] {standard_task_runner.py:77} INFO - Running: ['airflow', 'run', 'clean_data', 'merge_data', '2021-03-04T21:44:31.403251+00:00', '--job_id', '100', '--pool', 'default_pool', '--raw', '-sd', 'DAGS_FOLDER/data_clean.py', '--cfg_path', '/tmp/tmpa366magz']
[2021-03-04 21:46:22,803] {standard_task_runner.py:78} INFO - Job 100: Subtask merge_data
[2021-03-04 21:46:22,935] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: clean_data.merge_data 2021-03-04T21:44:31.403251+00:00 [running]> 6623e80cd770
[2021-03-04 21:46:23,219] {python_operator.py:114} INFO - Done. Returned value was: None
[2021-03-04 21:46:23,232] {taskinstance.py:1070} INFO - Marking task as SUCCESS.dag_id=clean_data, task_id=merge_data, execution_date=20210304T214431, start_date=20210304T214622, end_date=20210304T214623
[2021-03-04 21:46:27,679] {local_task_job.py:102} INFO - Task exited with return code 0
