[2021-03-05 01:36:58,813] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: clean_data.merge_data 2021-03-05T01:35:21.765790+00:00 [queued]>
[2021-03-05 01:36:58,835] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: clean_data.merge_data 2021-03-05T01:35:21.765790+00:00 [queued]>
[2021-03-05 01:36:58,835] {taskinstance.py:880} INFO - 
--------------------------------------------------------------------------------
[2021-03-05 01:36:58,836] {taskinstance.py:881} INFO - Starting attempt 1 of 2
[2021-03-05 01:36:58,836] {taskinstance.py:882} INFO - 
--------------------------------------------------------------------------------
[2021-03-05 01:36:58,861] {taskinstance.py:901} INFO - Executing <Task(PythonOperator): merge_data> on 2021-03-05T01:35:21.765790+00:00
[2021-03-05 01:36:58,864] {standard_task_runner.py:54} INFO - Started process 1837 to run task
[2021-03-05 01:36:58,886] {standard_task_runner.py:77} INFO - Running: ['airflow', 'run', 'clean_data', 'merge_data', '2021-03-05T01:35:21.765790+00:00', '--job_id', '47', '--pool', 'default_pool', '--raw', '-sd', 'DAGS_FOLDER/data_clean.py', '--cfg_path', '/tmp/tmpy28d898z']
[2021-03-05 01:36:58,889] {standard_task_runner.py:78} INFO - Job 47: Subtask merge_data
[2021-03-05 01:36:58,956] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: clean_data.merge_data 2021-03-05T01:35:21.765790+00:00 [running]> 6623e80cd770
[2021-03-05 01:36:59,158] {python_operator.py:114} INFO - Done. Returned value was: None
[2021-03-05 01:36:59,175] {taskinstance.py:1070} INFO - Marking task as SUCCESS.dag_id=clean_data, task_id=merge_data, execution_date=20210305T013521, start_date=20210305T013658, end_date=20210305T013659
[2021-03-05 01:37:03,798] {local_task_job.py:102} INFO - Task exited with return code 0
