[2021-03-04 21:36:55,274] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: clean_data.merge_data 2021-03-04T21:35:12.457746+00:00 [queued]>
[2021-03-04 21:36:55,305] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: clean_data.merge_data 2021-03-04T21:35:12.457746+00:00 [queued]>
[2021-03-04 21:36:55,305] {taskinstance.py:880} INFO - 
--------------------------------------------------------------------------------
[2021-03-04 21:36:55,306] {taskinstance.py:881} INFO - Starting attempt 1 of 2
[2021-03-04 21:36:55,306] {taskinstance.py:882} INFO - 
--------------------------------------------------------------------------------
[2021-03-04 21:36:55,332] {taskinstance.py:901} INFO - Executing <Task(PythonOperator): merge_data> on 2021-03-04T21:35:12.457746+00:00
[2021-03-04 21:36:55,336] {standard_task_runner.py:54} INFO - Started process 6940 to run task
[2021-03-04 21:36:55,361] {standard_task_runner.py:77} INFO - Running: ['airflow', 'run', 'clean_data', 'merge_data', '2021-03-04T21:35:12.457746+00:00', '--job_id', '94', '--pool', 'default_pool', '--raw', '-sd', 'DAGS_FOLDER/data_clean.py', '--cfg_path', '/tmp/tmp0il_l9at']
[2021-03-04 21:36:55,365] {standard_task_runner.py:78} INFO - Job 94: Subtask merge_data
[2021-03-04 21:36:55,414] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: clean_data.merge_data 2021-03-04T21:35:12.457746+00:00 [running]> 6623e80cd770
[2021-03-04 21:36:55,563] {python_operator.py:114} INFO - Done. Returned value was: None
[2021-03-04 21:36:55,582] {taskinstance.py:1070} INFO - Marking task as SUCCESS.dag_id=clean_data, task_id=merge_data, execution_date=20210304T213512, start_date=20210304T213655, end_date=20210304T213655
[2021-03-04 21:37:00,256] {local_task_job.py:102} INFO - Task exited with return code 0
